// AUTO-GENERATED FILE.
// This file is auto-generated by the Ballerina OpenAPI tool.

import ballerina/http;
import ballerina/test;

configurable http:BearerTokenConfig & readonly authConfig = ?;
ConnectionConfig config = {auth : authConfig};
Client baseClient = check new Client(config, serviceUrl = "https://api.hubapi.com");

@test:Config {}
isolated function  testGet-/crm/v3/objects/feedback_submissions/{feedbackSubmissionId}_getById() {
}

@test:Config {}
isolated function  testPost-/crm/v3/objects/feedback_submissions/batch/read_read() {
}

@test:Config {}
isolated function  testPost-/crm/v3/objects/feedback_submissions/search_doSearch() {
}

@test:Config {}
isolated function  testGet-/crm/v3/objects/feedback_submissions_getPage() {
}
