// AUTO-GENERATED FILE. DO NOT MODIFY.
// This file is auto-generated by the Ballerina OpenAPI tool.

import ballerina/http;
import ballerina/test;

configurable http:BearerTokenConfig & readonly authConfig = ?;
ConnectionConfig config = {auth : authConfig};
final Client baseClient = check new Client(config, serviceUrl = "https://api.hubapi.com");


final string feedbackSubmissionId = "392710142127";

@test:Config {}
isolated function getPageOfFeedbackSubmissions() returns error? {
    CollectionResponseSimplePublicObjectWithAssociationsForwardPaging response = check baseClient->/crm/v3/objects/feedback_submissions;
    test:assertTrue(response?.results.length()>=0);                                              
}

@test:Config {}
isolated function  getFeedbackSubmissionById() returns error? { 
    SimplePublicObjectWithAssociations response = check baseClient->/crm/v3/objects/feedback_submissions/[feedbackSubmissionId];
    test:assertTrue(response?.properties == 
            {   
            "hs_createdate": "2024-12-21T11:39:24.734Z",
            "hs_lastmodifieddate": "2024-12-21T11:39:25.742Z",
            "hs_object_id": "392710142127"
            }   
        );
}

// @test:Config {}
// isolated function  testPost-/crm/v3/objects/feedback_submissions/batch/read_read() {
// }

// @test:Config {}
// isolated function  searchFeedbackSubmissions() returns error?{
//     CollectionResponseWithTotalSimplePublicObjectForwardPaging response = check baseClient->/crm/v3/objects/feedback_submissions/search.post({
//         payload = {
            
//         }
//     });
// }


